### ISSUE TITLE
Should there be a Find-GCEInstance like the Find-GCSObject?

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-powershell#101]
Trying to take on the scenario listing all VMs

**Comment by ILMTitan** [comment]
I would argue the functionality of Find-GcsObject should be part of Get-GcsObject. I am in favor of fewer cmdlets that do more, so the user has an easier time finding the cmdlet they need, and then another small task to figure out how to use it, rather than one big task of finding the exact right cmdlet to use.
