### ISSUE TITLE
Edit cmdlet ref website to improve discovery and navigation  [userstudy]

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-powershell#217]
I can take point making alternative design suggestions.

**Comment by chrsmith** [comment]
Please do. @marceloyuela is looking into creating the new Angular frontend, so we can have better formatting, etc. But we could certainly use some help in how to actually render the data.

For reference, here are the cmdlet references for:

- [Azure](https://msdn.microsoft.com/en-us/library/mt619274.aspx)
- [AWS](http://docs.aws.amazon.com/powershell/latest/reference/Index.html)

We'll probably want to just match Amazon's, since the Azure one adds to much unnecessary hierarchy.

**Comment by marceloyuela** [comment]
@YnR sent you a doc with a rough draft for design.

**Comment by chrsmith** [comment]
Update: Lots of discussion internally, have mocks for a new website. Once in wireframes with pixel offsets, will start working on the HTML and CSS.

**Comment by chrsmith** [comment]
New website is live at:
googlecloudplatform.github.io/google-cloud-powershell/
