### ISSUE TITLE
Order the syntax summary putting the most likely scenario first.  [userstudy]

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-powershell#220]
Like `-AddDisk` for `set-GCEInstance` or `New-GCSObject -File` vs `-Content`

**Comment by ILMTitan** [comment]
I will have to examine how that gets ordered in the first place.

**Comment by chrsmith** [comment]
It's possible to reorder the cmdlet parameters, which would then influence the way the "syntax" view gets displayed. However that doesn't meet the bar for a reasonable code change. (Lots of churn, negligible benefit.) Also, while we can gather data about which parametersets are the most common, it doesn't seem like a good use of time (adjusting the parameters in code so that everything lines up).

With the new website we'll try to make the syntax view easier to understand (perhaps with colors? or some other differentiation). And also, place a larger emphasis on examples would have a more dramatic impact on usability.
