### ISSUE TITLE
New-GCEDisk -SizeGB accepts a string, parses it wrong (10G => 10^9 instead of 10GB) [userstudy]

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-powershell#241]

**Comment by ILMTitan** [comment]
This is a powershell thing and not something we can fix.
PS C:\> [long] 10GB

**Comment by chrsmith** [comment]
We accept the value as a long, so PowerShell owns the parsing of "10GB" as it is conferted to megabytes.

https://github.com/GoogleCloudPlatform/google-cloud-powershell/blob/888a70c4c433fdd302a3f11ceced0304f24e7456/Google.PowerShell/Compute/GceDisk.cs#L205

However, it does look like PowerShell is interpreting "10GB" as "10GiB":

````
C:\src\github.com\chrsmith\google-cloud-powershell [gcs-object-metadata]> $x = 10GB
C:\src\github.com\chrsmith\google-cloud-powershell [gcs-object-metadata]> $x
10737418240
````

Pedantry aside, there is nothing we can do here.

**Comment by YnR** [comment]
Naive idea: Can we accept both a string and long for this, and do the parsing ourselves if they pass a string?

**Comment by chrsmith** [comment]
@YnR We could, but we shouldn't try to second guess or redefine semantics of the PowerShell platform.

The number "10GB" has a [specific meaning](http://stackoverflow.com/questions/24474017/what-is-the-full-list-of-number-suffixes-in-powershell) in PowerShell as per its spec, and we shouldn't try to reinterpret that.

Also, I don't see the user scenario here. I don't think it would actually impact people to be given 10GB of space and not 10GiB, right? Or do we expect people to know the amount of storage space they need on a VM to the megabyte? (Note that you get a warning, at least in `gcloud`, if your VM contains less than 200GiB of disk space. That's because any smaller than that you get a perf hit from the disk controller or something. http://stackoverflow.com/questions/35706605/gcloud-gce-disk-size-warning-is-it-meaningful)
