### ISSUE TITLE
Remove unapproved verbs from module

### ISSUE THREAD

**Issue by KirkMunro** [GoogleCloudPlatform/google-cloud-powershell#318]
Today you have the following commands that use unapproved verbs:

Failover-GcSqlInstance
Promote-GcSqlReplica

Use of unapproved verbs in exported module command names is strongly discouraged (to the point where many teams are simply told not to do it under any circumstances).

Instead of Failover-GcSqlInstance, consider:

Invoke-GcSqlInstanceFailover

Instead of Promote-GcSqlReplica, consider:

Convert-GcSqlReplicaToInstance

There are other possible verbs you can choose from of course and what I provided are just some that I feel work fine for what you need, but regardless of which you choose, the core command should have an approved verb.  If you really, _really_ feel the need for these names, define them as aliases for commands that use approved verbs.  In the long run I don't feel it's worth it (it's a best practice to avoid using aliases in scripts), and aliases like these are usually only kept around to maintain backwards compatibility with names that had to change for some reason.

**Comment by ILMTitan** [comment]
Thank you. Those look like good alternative names.

**Comment by chrsmith** [comment]
Notes on investigation so far:

Replacing `Failover-` with `Invoke-GcSqlInstanceFailover` sounds good. As for `Promote-`, since the conversion isn't bidirectional, we should use `ConvertTo-GcSqlInstance` ([docs](https://msdn.microsoft.com/en-us/library/ms714428(v=vs.85).aspx)).

We'll need to make this change before exiting Beta, since at that point we won't be able to make breaking changes like this. However, even at this point we still need to go through and update documentation (e.g. on cloud.google.com) to mention the changes.

**Comment by rrxtns** [comment]
@chrsmith `Convert-GcSqlInstance` would be more in line with the naming convention (though admittedly, it may be non specific enough)

**Comment by KirkMunro** [comment]
@rrxtns Actually if you just use the Convert verb, it sounds like you are converting a GcSqlInstance, as opposed to converting to a GcSqlInstance (which is what I believe is actually happening).

@chrsmith I like the ConvertTo-GcSqlInstance name for that command, and good catch on that being the guidance as per the docs.

**Comment by quoctruong** [comment]
This is fixed with https://github.com/GoogleCloudPlatform/google-cloud-powershell/pull/359. We changed the cmdlets to ConvertTo-GcSqlInstance and Invoke-GcSqlInstanceFailover.
